services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - data-postgres:/var/lib/postgres
    ports:
      - "5432:5432"
volumes:
  data-postgres:
